"""empty message

Revision ID: 1f80b7ecc837
Revises: 20de1e341c13
Create Date: 2018-07-18 22:05:00.012402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f80b7ecc837'
down_revision = '20de1e341c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_description_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_description_key', 'product', ['description'])
    # ### end Alembic commands ###
