"""empty message

Revision ID: 6fb7c3155ac2
Revises: 3f1fb70432c3
Create Date: 2018-07-16 18:04:16.354156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb7c3155ac2'
down_revision = '3f1fb70432c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeseries', sa.Column('latitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeseries', 'latitude')
    # ### end Alembic commands ###
